ren	F:\htdocs\prestashop\mails\en-gb									en
ren	F:\htdocs\prestashop\themes\prestashop\lang\en-gb.php									en.php
ren	F:\htdocs\prestashop\themes\tuding\lang\en-gb.php									en.php
ren	F:\htdocs\prestashop\translations\en-gb									en



ren	F:\htdocs\prestashop\modules\birthdaypresent\mails\en-gb									en
ren	F:\htdocs\prestashop\modules\blocknewsletter\mails\en-gb									en
ren	F:\htdocs\prestashop\modules\blockwishlist\mails\en-gb									en
ren	F:\htdocs\prestashop\modules\followup\mails\en-gb									en
ren	F:\htdocs\prestashop\modules\mailalerts\mails\en-gb									en
ren	F:\htdocs\prestashop\modules\referralprogram\mails\en-gb									en
ren	F:\htdocs\prestashop\modules\sendtoafriend\mails\en-gb									en



ren	F:\htdocs\prestashop\modules\authorizeaim\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\autoupgrade\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\bankwire\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\birthdaypresent\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\blockadvertising\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\blockbestsellers\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\blockcart\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\blockcategories\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\blockcms\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\blockcurrencies\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\blockcustomerprivacy\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\blocklanguages\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\blocklayered\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\blocklink\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\blockmanufacturer\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\blockmyaccount\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\blocknewproducts\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\blocknewsletter\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\blockpaymentlogo\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\blockpermanentlinks\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\blockrss\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\blocksearch\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\blockspecials\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\blockstore\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\blocksupplier\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\blocktags\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\blockuserinfo\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\blockviewed\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\blockwishlist\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\canadapost\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\cashondelivery\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\cheque\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\criteo\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\crossselling\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\editorial\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\feeder\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\followup\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\gadsense\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\ganalytics\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\gcheckout\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\graphartichow\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\graphgooglechart\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\graphvisifire\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\graphxmlswfcharts\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\gridhtml\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\gsitemap\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\homefeatured\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\importerosc\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\livezilla\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\loyalty\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\mailalerts\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\mondialrelay\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\moneybookers\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\newsletter\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\pagesnotfound\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\paypal\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\paysafecard\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\prestafraud\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\productcomments\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\productscategory\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\producttooltip\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\referralprogram\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\secuvad\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\sekeywords\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\sendtoafriend\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\shopimporter\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\socolissimo\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\statsbestcategories\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\statsbestcustomers\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\statsbestmanufacturers\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\statsbestproducts\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\statsbestsuppliers\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\statsbestvouchers\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\statscarrier\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\statscatalog\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\statscheckup\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\statsdata\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\statsequipment\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\statsforecast\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\statsgeolocation\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\statslive\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\statsnewsletter\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\statsorigin\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\statspersonalinfos\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\statsproduct\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\statsregistrations\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\statssales\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\statssearch\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\statsstock\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\statsvisits\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\themeinstallator\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\trackingfront\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\treepodia\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\trustedshops\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\twenga\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\upscarrier\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\uspscarrier\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\vatnumber\en-gb.php									en.php
ren	F:\htdocs\prestashop\modules\watermark\en-gb.php									en.php
